#!/bin/bash

# 메타 숫타 앱 깃헙브 설정 안내

set -e

echo "📊 메타 숫타 앱 - 깃헙브 설정 가이드"
echo "=========================================="
echo ""

echo "프로젝트 정보:"
echo "  이름: metta-sutta-app"
echo "  설명: 팔리어 경전 연구 앱 - 메타 숫타 (자비경 연구)"
echo "  언어: TypeScript + React"
echo "  프레임워크: Next.js"
echo ""

echo "깃헙브 설정 옵션 두 가지가 있습니다:"
echo ""

echo "🔹 옵션 A: GitHub Project (프라이빗 - 무료)"
echo "  - 장점: 완전 무료, CI/CD 자동화, 300MB 저장 공간"
echo "  - 단점: 비공개 설정 불가 (프라이빗 제한)"
echo "  - 웹 인터페이스 설정 방법:"
echo "    1. https://github.com/new 접속"
echo "    2. 'Repository name'에 'metta-sutta-app' 입력"
echo "    3. 'Description'에 '팔리어 경전 연구 앱 - 메타 숫타' 입력"
echo "    4. 'Add .gitignore' 체크"
echo "    5. 'Create repository' 클릭"
echo "    6. 생성 후, 프로젝트 디렉토리에 git init, git add, git commit 수행"
echo ""
echo "  - CI/CD 설정:"
echo "    1. Settings → Pages → Branch → 'Add file' → New file'"
echo "    2. '.github/workflows/deploy.yml' 이름으로 생성"
echo "    3. 다음 내용 입력:"
echo ""
echo "name: Deploy to GitHub Pages"
echo "on:"
echo "  push:"
echo "    branches: [main]"
echo "jobs:"
echo "  build:"
echo "    runs-on: ubuntu-latest"
echo "    steps:"
echo "      - uses: actions/checkout@v4"
echo "      - name: Setup Node.js"
echo "        uses: actions/setup-node@v4"
echo "        with:"
echo "          node-version: '20'"
echo "      - name: Install dependencies"
echo "        run: npm ci"
echo "      - name: Build"
echo "        run: npm run build"
echo "      - name: Upload artifact"
echo "        uses: actions/upload-artifact@v4"
echo "        with:"
echo "          name: build"
echo "          path: .next"
echo "  deploy:"
echo "    environment:"
echo "      name: github_pages"
echo "      url: ${{ steps.deployment.outputs.page_url }}"
echo "    runs-on: ubuntu-latest"
echo "    needs: build"
echo "    steps:"
echo "      - name: Deploy to GitHub Pages"
echo "        uses: peaceiris/actions-gh-pages@v3"
echo "        with:"
echo "          github_token: ${{ secrets.GITHUB_TOKEN }}"
echo "          publish_dir: .next"
echo ""

echo "✅ 옵션 B: GitHub Codespaces (프라이빗 + 저장소)"
echo "  - 장점: 완전 무료, 온라인 IDE, 30GB 저장소"
echo "  - 단점: 비공개 설정 불가 (프라이빗 제한)"
echo "  - 설정 방법:"
echo "    1. https://github.com/codespaces/new 접속"
echo "    2. 'Create codespace' 클릭"
echo "    3. 'Repository name'에 'metta-sutta-app' 입력"
echo "    4. 'Visibility'는 비워두기"
echo "    5. 'Project type'을 'Blank Project'로 설정"
echo "    6. 'Template'은 선택하지 않음"
echo "    7. 'Create codespace' 클릭"
echo "    8. 생성된 Codespace에서 클론 후 터미널에서 작업"
echo ""
echo "  - 프로젝트 클론 방법:"
echo "    1. Codespace UI에서 'Code' 탭 → 'Clone' → 'Local' 클릭"
echo "    2. 또는 터미널에서: git clone https://github.com/YOUR_USERNAME/metta-sutta-app.git"
echo "    3. 로컬에서 프로젝트 폴더로 이동"
echo "    4. npm install && npm run dev"
echo ""
echo "  - 배포 방법 (GitHub Pages):"
echo "    1. 'gh auth login'로 로그인"
echo "    2. 프로젝트 폴더에서: gh repo set-default --public"
echo "    3. 배포: gh workflow deploy"
echo ""

echo "🔐 옵션 C: GitHub Organization Repository (비공개)"
echo "  - 장점: 완전 무료, 비공개 설정 가능, CI/CD 자동화"
echo "  - 단점: 무료 계정에서 팀 제한 (최대 2인)"
echo "  - 설정 방법:"
echo "    1. GitHub 오른쪽 상단 '+' → 'New repository' 클릭"
echo "    2. 'Owner'에서 조직(조직이 없으면 생성) 선택"
echo "    3. 'Repository name'에 'metta-sutta-app' 입력"
echo "    4. 'Description'에 설명 입력"
echo "    5. 'Visibility'는 비워두기"
echo "    6. 'Add .gitignore' 체크"
echo "    7. 'Create repository' 클릭"
echo "    8. 'Initialize this repository with'은 'Add README file' 체크 후 'Initialize with README.md' 선택"
echo ""
echo "  - CI/CD 설정:"
echo "    1. Repository 생성 후, 'Settings' → 'Secrets and variables → Actions' → 'New repository secret'"
echo "    2. 'Name'에 'VERCEL_TOKEN' 입력"
echo "    3. 'Value'에 Vercel API Token 입력 (Vercel에서 발급)"
echo "    4. 'Add secret' 클릭"
echo "    5. 'Settings' → 'Actions' → 'General' → 'Workflow permissions' → 'Contents: Read and write permissions' 설정"
echo ""
echo "  - 배포 방법:"
echo "    1. Vercel 설치 후 'vercel login'"
echo "    2. 'vercel link'로 연결"
echo "    3. 'vercel deploy'로 배포 (자동 배포 URL 제공)"
echo ""

echo "=========================================="
echo ""
echo "💡 추천:"
echo "  - 시작하려면 옵션 A 또는 옵션 B (프라이빗)을 추천"
echo "  - Vercel 배포가 더 쉽고 안정적입니다"
echo "  - 비공개 설정이 필요하다면 옵션 C (Organization Repository)을 사용"
echo ""
echo "❓ 도움말기:"
echo "  - GitHub 팀 캣틱: https://github.com/teams"
echo "  - Vercel 도큐멘테이션: https://vercel.com/docs"
echo ""
